# Generated by Django 3.1.2 on 2020-10-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='total_rating',
            field=models.FloatField(default=4.2),
            preserve_default=False,
        ),
    ]
