# Generated by Django 3.1.2 on 2020-11-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_shop_total_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.CharField(default='https://tabelog.com/hyogo/A2801/A280101/28043971/', max_length=256),
            preserve_default=False,
        ),
    ]
