# Generated by Django 3.1.2 on 2020-11-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_usershop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usershop',
            old_name='shop',
            new_name='shops',
        ),
    ]
