# Generated by Django 3.1.2 on 2020-11-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201114_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='search_query',
        ),
        migrations.AddField(
            model_name='search',
            name='category_code',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='place_code',
            field=models.CharField(default='test1', max_length=128),
            preserve_default=False,
        ),
    ]
